name: build

on:
  push:
    branches:
      - main
      - '*'
    tags:
      - '*'
  schedule:
    - cron: '15 0 1 * *'
  workflow_dispatch:
    inputs:

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - if: github.ref == 'refs/heads/main'
        name: Conditional(Set tag as `latest`)
        env: # Or as an environment variable
          docker_repo: ${{ secrets.DOCKER_REPO }}
        run: echo "tag=${{env.docker_repo}}/gtfy2ntfy:latest" >> $GITHUB_ENV

      - if: startsWith(github.ref, 'refs/tags/')
        name: Conditional(Set tag as `{version}`)
        env: # Or as an environment variable
          docker_repo: ${{ secrets.DOCKER_REPO }}
        run: |
          echo "docker_repo = ${{env.docker_repo}}"
          echo "tag=${{env.docker_repo}}/gtfy2ntfy:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - if: github.ref != 'refs/heads/main' && startsWith(github.ref, 'refs/heads/')
        name: Conditional(Set tag as `{version}`)
        env: # Or as an environment variable
          docker_repo: ${{ secrets.DOCKER_REPO }}
        run: |
          echo "docker_repo = ${{env.docker_repo}}"
          echo "tag=${{env.docker_repo}}/gtfy2ntfy:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.tag }}
