name: docker-image

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Build Docker image 
        run: docker build . -t="gtfy-listener"
      - name: Remove test build image
        run: docker rmi $(docker image ls -q)